### ISSUE TITLE
Port option

### ISSUE THREAD

**Issue by mkgrgis** [ibarwick/fbsql#2]
[feature request]
Option for Firebird database port.

**Comment by ibarwick** [comment]
Try specifying the port as part of the database connection string, e.g.:

```
$ ./src/fbsql -d localhost/3051:employee -u sysdba -p masterkey
fbsql 0.2.0
Connected to Firebird v4.0.0 (libfq version 0.4.1)
SQL> 
```

See also: http://www.firebirdfaq.org/faq259/

**Comment by mkgrgis** [comment]
Thanks for the explanation. For the same reasons there is no host option in fbsql. I was looking for something hard psql-styled.
